services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootroot
      MYSQL_DATABASE: fit_react_db
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server
    restart: always
    environment:
      - DB_HOST=mysql # Use 'mysql' as the hostname
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=rootroot
      - DB_NAME=fit_react_db
      - JWT_SECRET=4c0d608098b78d61cf5654965dab8b53632bf831dc6b43f29289411376ac107b
      - REFRESH_TOKEN_SECRET=c4a71ea639f6de11f146f21193d91c4518a3c285f1853d44778910d6130a4c03
    depends_on:
      - mysql
    ports:
      - "3001:3001"
    volumes:
      - .:/app

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - server

volumes:
  mysql-data:
